version: '3.8'

services:
  usercrud:
    image: usercrud-app
    build:
      context: .
    ports:
      - "8082:8082"
    expose:
      - "8082"  # needed for nginx to reach it internally

  nginx:
    image: nginx
    ports:
      - "8083:80"  # You access nginx on localhost:8083
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - usercrud
